# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = E:\VulkanEngineMain

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = E:\VulkanEngineMain

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start E:\VulkanEngineMain\CMakeFiles E:\VulkanEngineMain\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start E:\VulkanEngineMain\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Shaders

# Build rule for target.
Shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 Shaders
.PHONY : Shaders

# fast build rule for target.
Shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Shaders.dir\build.make CMakeFiles/Shaders.dir/build
.PHONY : Shaders/fast

#=============================================================================
# Target rules for targets named vkbootstrap

# Build rule for target.
vkbootstrap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 vkbootstrap
.PHONY : vkbootstrap

# fast build rule for target.
vkbootstrap/fast:
	$(MAKE) $(MAKESILENT) -f third_party\CMakeFiles\vkbootstrap.dir\build.make third_party/CMakeFiles/vkbootstrap.dir/build
.PHONY : vkbootstrap/fast

#=============================================================================
# Target rules for targets named tinyobjloader

# Build rule for target.
tinyobjloader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 tinyobjloader
.PHONY : tinyobjloader

# fast build rule for target.
tinyobjloader/fast:
	$(MAKE) $(MAKESILENT) -f third_party\CMakeFiles\tinyobjloader.dir\build.make third_party/CMakeFiles/tinyobjloader.dir/build
.PHONY : tinyobjloader/fast

#=============================================================================
# Target rules for targets named lz4

# Build rule for target.
lz4: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lz4
.PHONY : lz4

# fast build rule for target.
lz4/fast:
	$(MAKE) $(MAKESILENT) -f third_party\CMakeFiles\lz4.dir\build.make third_party/CMakeFiles/lz4.dir/build
.PHONY : lz4/fast

#=============================================================================
# Target rules for targets named fmt_lib

# Build rule for target.
fmt_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 fmt_lib
.PHONY : fmt_lib

# fast build rule for target.
fmt_lib/fast:
	$(MAKE) $(MAKESILENT) -f third_party\CMakeFiles\fmt_lib.dir\build.make third_party/CMakeFiles/fmt_lib.dir/build
.PHONY : fmt_lib/fast

#=============================================================================
# Target rules for targets named spirv_reflect

# Build rule for target.
spirv_reflect: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 spirv_reflect
.PHONY : spirv_reflect

# fast build rule for target.
spirv_reflect/fast:
	$(MAKE) $(MAKESILENT) -f third_party\CMakeFiles\spirv_reflect.dir\build.make third_party/CMakeFiles/spirv_reflect.dir/build
.PHONY : spirv_reflect/fast

#=============================================================================
# Target rules for targets named imgui

# Build rule for target.
imgui: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 imgui
.PHONY : imgui

# fast build rule for target.
imgui/fast:
	$(MAKE) $(MAKESILENT) -f third_party\CMakeFiles\imgui.dir\build.make third_party/CMakeFiles/imgui.dir/build
.PHONY : imgui/fast

#=============================================================================
# Target rules for targets named logger

# Build rule for target.
logger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 logger
.PHONY : logger

# fast build rule for target.
logger/fast:
	$(MAKE) $(MAKESILENT) -f src\CMakeFiles\logger.dir\build.make src/CMakeFiles/logger.dir/build
.PHONY : logger/fast

#=============================================================================
# Target rules for targets named vulkan_guide

# Build rule for target.
vulkan_guide: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 vulkan_guide
.PHONY : vulkan_guide

# fast build rule for target.
vulkan_guide/fast:
	$(MAKE) $(MAKESILENT) -f src\CMakeFiles\vulkan_guide.dir\build.make src/CMakeFiles/vulkan_guide.dir/build
.PHONY : vulkan_guide/fast

#=============================================================================
# Target rules for targets named assetlib

# Build rule for target.
assetlib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 assetlib
.PHONY : assetlib

# fast build rule for target.
assetlib/fast:
	$(MAKE) $(MAKESILENT) -f assetlib\CMakeFiles\assetlib.dir\build.make assetlib/CMakeFiles/assetlib.dir/build
.PHONY : assetlib/fast

#=============================================================================
# Target rules for targets named baker

# Build rule for target.
baker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 baker
.PHONY : baker

# fast build rule for target.
baker/fast:
	$(MAKE) $(MAKESILENT) -f asset_baker\CMakeFiles\baker.dir\build.make asset_baker/CMakeFiles/baker.dir/build
.PHONY : baker/fast

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... Shaders
	@echo ... assetlib
	@echo ... baker
	@echo ... fmt_lib
	@echo ... imgui
	@echo ... logger
	@echo ... lz4
	@echo ... spirv_reflect
	@echo ... tinyobjloader
	@echo ... vkbootstrap
	@echo ... vulkan_guide
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

